// Ported verbatim from Sources/Envy/EmojiShortcodes.swift — extracted
// mechanically rather than retyped, since a Swift dictionary literal of
// string pairs is already valid TypeScript.
//
/// GitHub/Slack-style `:shortcode:` names mapped to their emoji. Typing a
/// colon that completes a known shortcode replaces the whole ":word:" span
/// with the real emoji character — the saved note just contains the emoji
/// itself, no special syntax to render.
export const EMOJI_SHORTCODES: Record<string, string> = {
        "smile": "😄", "smiley": "😃", "grin": "😁", "laughing": "😆", "satisfied": "😆",
        "sweat_smile": "😅", "joy": "😂", "rofl": "🤣", "relaxed": "☺️", "blush": "😊",
        "innocent": "😇", "slight_smile": "🙂", "upside_down": "🙃", "wink": "😉",
        "relieved": "😌", "heart_eyes": "😍", "kissing_heart": "😘", "kissing": "😗",
        "kissing_smiling_eyes": "😙", "kissing_closed_eyes": "😚", "yum": "😋",
        "stuck_out_tongue": "😛", "stuck_out_tongue_winking_eye": "😜",
        "stuck_out_tongue_closed_eyes": "😝", "money_mouth": "🤑", "nerd": "🤓",
        "sunglasses": "😎", "star_struck": "🤩", "clown": "🤡", "cowboy": "🤠",
        "smirk": "😏", "unamused": "😒", "disappointed": "😞", "pensive": "😔",
        "worried": "😟", "confused": "😕", "slight_frown": "🙁", "frowning": "☹️",
        "persevere": "😣", "confounded": "😖", "tired_face": "😫", "weary": "😩",
        "triumph": "😤", "angry": "😠", "rage": "😡", "cry": "😢", "sob": "😭",
        "sweat": "😓", "scream": "😱", "fearful": "😨", "cold_sweat": "😰",
        "hushed": "😯", "frowning_open": "😦", "anguished": "😧", "flushed": "😳",
        "dizzy_face": "😵", "exploding_head": "🤯", "nauseated": "🤢",
        "sneezing": "🤧", "hot_face": "🥵", "cold_face": "🥶", "woozy": "🥴",
        "thinking": "🤔", "zipper_mouth": "🤐", "raised_eyebrow": "🤨",
        "neutral_face": "😐", "expressionless": "😑", "no_mouth": "😶",
        "smirking": "😼", "roll_eyes": "🙄", "sleepy": "😪", "drooling": "🤤",
        "sleeping": "😴", "mask": "😷", "thermometer_face": "🤒", "bandage_face": "🤕",
        "shush": "🤫", "lying": "🤥", "vomiting": "🤮", "yawning": "🥱",
        "ghost": "👻", "skull": "💀", "alien": "👽", "robot": "🤖", "poop": "💩",
        "smiling_imp": "😈", "imp": "👿", "japanese_ogre": "👹", "japanese_goblin": "👺",
        "heart": "❤️", "orange_heart": "🧡", "yellow_heart": "💛", "green_heart": "💚",
        "blue_heart": "💙", "purple_heart": "💜", "black_heart": "🖤", "white_heart": "🤍",
        "brown_heart": "🤎", "broken_heart": "💔", "heartbeat": "💓", "heartpulse": "💗",
        "sparkling_heart": "💖", "cupid": "💘", "gift_heart": "💝", "two_hearts": "💕",
        "revolving_hearts": "💞", "love_letter": "💌",
        "thumbsup": "👍", "+1": "👍", "thumbsdown": "👎", "-1": "👎",
        "ok_hand": "👌", "pinched_fingers": "🤌", "pinching_hand": "🤏",
        "v": "✌️", "crossed_fingers": "🤞", "love_you": "🤟", "metal": "🤘",
        "call_me": "🤙", "point_left": "👈", "point_right": "👉", "point_up_2": "👆",
        "point_down": "👇", "point_up": "☝️", "raised_hand": "✋", "raised_back_hand": "🤚",
        "hand_splayed": "🖐️", "vulcan": "🖖", "wave": "👋", "clap": "👏",
        "raised_hands": "🙌", "open_hands": "👐", "palms_up": "🤲", "handshake": "🤝",
        "pray": "🙏", "writing_hand": "✍️", "muscle": "💪", "fist": "✊",
        "facepunch": "👊", "left_facing_fist": "🤛", "right_facing_fist": "🤜",
        "fire": "🔥", "star": "⭐", "star2": "🌟", "sparkles": "✨", "zap": "⚡",
        "boom": "💥", "collision": "💥", "tada": "🎉", "confetti_ball": "🎊",
        "balloon": "🎈", "gift": "🎁", "trophy": "🏆", "medal": "🏅",
        "100": "💯", "warning": "⚠️", "no_entry": "⛔", "x": "❌", "heavy_check_mark": "✔️",
        "white_check_mark": "✅", "question": "❓", "exclamation": "❗",
        "bulb": "💡", "eyes": "👀", "eye": "👁️", "brain": "🧠", "bone": "🦴",
        "tooth": "🦷", "speech_balloon": "💬", "thought_balloon": "💭",
        "zzz": "💤", "hourglass": "⌛", "hourglass_flowing": "⏳", "clock": "🕐",
        "alarm_clock": "⏰", "watch": "⌚", "calendar": "📅", "date": "📆",
        "pushpin": "📌", "round_pushpin": "📍", "paperclip": "📎", "link": "🔗",
        "lock": "🔒", "unlock": "🔓", "key": "🔑", "hammer": "🔨", "wrench": "🔧",
        "gear": "⚙️", "mag": "🔍", "bell": "🔔", "no_bell": "🔕", "mute": "🔇",
        "loud_sound": "🔊", "email": "📧", "envelope": "✉️", "inbox_tray": "📥",
        "outbox_tray": "📤", "package": "📦", "mailbox": "📫", "folder": "📁",
        "file_folder": "📁", "open_file_folder": "📂", "page_facing_up": "📄",
        "bookmark": "🔖", "book": "📖", "books": "📚", "notebook": "📓",
        "pencil": "📝", "memo": "📝", "pencil2": "✏️", "pen": "🖊️", "scissors": "✂️",
        "chart": "📈", "chart_decreasing": "📉", "bar_chart": "📊",
        "computer": "💻", "desktop": "🖥️", "keyboard": "⌨️", "printer": "🖨️",
        "phone": "☎️", "iphone": "📱", "camera": "📷", "video_camera": "📹",
        "tv": "📺", "battery": "🔋", "electric_plug": "🔌", "bulb2": "💡",
        "flashlight": "🔦", "candle": "🕯️", "moneybag": "💰", "dollar": "💵",
        "credit_card": "💳", "chart_money": "💹", "gem": "💎", "scales": "⚖️",
        "toolbox": "🧰", "test_tube": "🧪", "microscope": "🔬", "telescope": "🔭",
        "satellite": "🛰️", "rocket": "🚀", "airplane": "✈️", "car": "🚗",
        "taxi": "🚕", "bus": "🚌", "train": "🚆", "bike": "🚲", "ship": "🚢",
        "anchor": "⚓", "construction": "🚧", "traffic_light": "🚦",
        "sun": "☀️", "cloud": "☁️", "cloud_rain": "🌧️", "cloud_lightning": "⛈️",
        "snowflake": "❄️", "snowman": "⛄", "umbrella": "☔", "rainbow": "🌈",
        "earth_americas": "🌎", "earth_africa": "🌍", "earth_asia": "🌏",
        "moon": "🌙", "full_moon": "🌕", "new_moon": "🌑", "night": "🌃",
        "tree": "🌳", "evergreen_tree": "🌲", "palm_tree": "🌴", "cactus": "🌵",
        "flower": "🌼", "rose": "🌹", "sunflower": "🌻", "tulip": "🌷",
        "leaves": "🍃", "maple_leaf": "🍁", "seedling": "🌱", "herb": "🌿",
        "four_leaf_clover": "🍀", "mushroom": "🍄",
        "dog": "🐶", "cat": "🐱", "mouse": "🐭", "rabbit": "🐰", "fox": "🦊",
        "bear": "🐻", "panda": "🐼", "koala": "🐨", "tiger": "🐯", "lion": "🦁",
        "cow": "🐮", "pig": "🐷", "frog": "🐸", "monkey": "🐵", "chicken": "🐔",
        "penguin": "🐧", "bird": "🐦", "owl": "🦉", "bat": "🦇", "wolf": "🐺",
        "horse": "🐴", "unicorn": "🦄", "bee": "🐝", "bug": "🐛", "butterfly": "🦋",
        "snail": "🐌", "turtle": "🐢", "snake": "🐍", "octopus": "🐙",
        "fish": "🐟", "whale": "🐳", "dolphin": "🐬", "shark": "🦈",
        "coffee": "☕", "tea": "🍵", "beer": "🍺", "beers": "🍻", "wine_glass": "🍷",
        "cocktail": "🍸", "tropical_drink": "🍹", "champagne": "🍾",
        "pizza": "🍕", "hamburger": "🍔", "fries": "🍟", "hotdog": "🌭",
        "taco": "🌮", "burrito": "🌯", "ramen": "🍜", "sushi": "🍣",
        "bento": "🍱", "rice": "🍚", "bread": "🍞", "cheese": "🧀", "egg": "🥚",
        "bacon": "🥓", "pancakes": "🥞", "apple": "🍎", "banana": "🍌",
        "grapes": "🍇", "watermelon": "🍉", "strawberry": "🍓", "cherries": "🍒",
        "peach": "🍑", "pineapple": "🍍", "lemon": "🍋", "avocado": "🥑",
        "carrot": "🥕", "corn": "🌽", "cake": "🍰", "birthday": "🎂",
        "cookie": "🍪", "chocolate_bar": "🍫", "candy": "🍬", "lollipop": "🍭",
        "doughnut": "🍩", "icecream": "🍦", "popcorn": "🍿",
        "house": "🏠", "office": "🏢", "school": "🏫", "hospital": "🏥",
        "bank": "🏦", "hotel": "🏨", "church": "⛪", "castle": "🏰",
        "world_map": "🗺️", "compass": "🧭", "mountain": "⛰️", "camping": "🏕️",
        "beach": "🏖️", "desert": "🏜️", "stadium": "🏟️",
        "party": "🥳", "celebrate": "🎉", "checkered_flag": "🏁", "flag": "🚩",
        "crown": "👑", "gem_stone": "💎", "ring": "💍", "trophy2": "🏆",
        "first_place": "🥇", "second_place": "🥈", "third_place": "🥉"
}
